-- SHOW TABLES ;
-- SHOW DATABASES ;


CREATE TABLE USERS (
    USER_ID VARCHAR(255) PRIMARY KEY ,
    USERNAME VARCHAR(255) UNIQUE ,
    EMAIL VARCHAR(255) UNIQUE NOT NULL ,
    PASSWORD VARCHAR(255) NOT NULL
) ;

SHOW TABLES ;